export type CountryCode =
  | "AR"
  | "AU"
  | "BR"
  | "CA"
  | "CL"
  | "CN"
  | "CO"
  | "DE"
  | "ES"
  | "FR"
  | "GB"
  | "IN"
  | "IT"
  | "JP"
  | "KR"
  | "MX"
  | "NZ"
  | "PE"
  | "PT"
  | "SG"
  | "US"
  | "UY"
  | "ZA";

export type BillingProviderKey = "mercadopago" | "stripe" | "paypal" | "manual";
export type MeasurementSystem = "metric" | "us";
export type TemperatureUnit = "celsius" | "fahrenheit";

export type CountryProfile = {
  code: CountryCode;
  name: string;
  region: string;
  locale: string;
  currency: string;
  timezone: string;
  taxIdLabel: string;
  taxLabel: string;
  defaultTaxRate: number;
  measurementSystem: MeasurementSystem;
  weightUnit: "kg" | "lb";
  volumeUnit: "l" | "gal";
  temperatureUnit: TemperatureUnit;
  dateFormat: "DD/MM/YYYY" | "MM/DD/YYYY" | "YYYY-MM-DD";
  billingProviders: BillingProviderKey[];
  labelLanguages: string[];
  foodAuthorities: string[];
  complianceFrameworks: string[];
  traceabilityFields: string[];
};

export const DEFAULT_COUNTRY_CODE: CountryCode = "AR";

export const COUNTRY_PROFILES: Record<CountryCode, CountryProfile> = {
  AR: {
    code: "AR",
    name: "Argentina",
    region: "LATAM",
    locale: "es-AR",
    currency: "ARS",
    timezone: "America/Argentina/Buenos_Aires",
    taxIdLabel: "CUIT",
    taxLabel: "IVA",
    defaultTaxRate: 21,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["mercadopago", "stripe", "paypal", "manual"],
    labelLanguages: ["es"],
    foodAuthorities: ["ANMAT", "SENASA", "ARCA"],
    complianceFrameworks: ["CAA", "RNE", "RNPA", "Ley 27.642", "BPM", "POES"],
    traceabilityFields: ["lote", "vencimiento", "RNE", "RNPA", "elaborador"],
  },
  UY: {
    code: "UY",
    name: "Uruguay",
    region: "LATAM",
    locale: "es-UY",
    currency: "UYU",
    timezone: "America/Montevideo",
    taxIdLabel: "RUT",
    taxLabel: "IVA",
    defaultTaxRate: 22,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["mercadopago", "stripe", "paypal", "manual"],
    labelLanguages: ["es"],
    foodAuthorities: ["MSP", "MGAP"],
    complianceFrameworks: ["BPM", "HACCP", "registro bromatologico"],
    traceabilityFields: ["lote", "vencimiento", "registro", "origen"],
  },
  CL: {
    code: "CL",
    name: "Chile",
    region: "LATAM",
    locale: "es-CL",
    currency: "CLP",
    timezone: "America/Santiago",
    taxIdLabel: "RUT",
    taxLabel: "IVA",
    defaultTaxRate: 19,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["mercadopago", "stripe", "paypal", "manual"],
    labelLanguages: ["es"],
    foodAuthorities: ["SEREMI de Salud", "SAG"],
    complianceFrameworks: ["RSA", "HACCP", "BPM", "Ley de etiquetado"],
    traceabilityFields: ["lote", "vencimiento", "resolucion sanitaria", "origen"],
  },
  BR: {
    code: "BR",
    name: "Brasil",
    region: "LATAM",
    locale: "pt-BR",
    currency: "BRL",
    timezone: "America/Sao_Paulo",
    taxIdLabel: "CNPJ",
    taxLabel: "ICMS",
    defaultTaxRate: 18,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["mercadopago", "stripe", "paypal", "manual"],
    labelLanguages: ["pt"],
    foodAuthorities: ["ANVISA", "MAPA"],
    complianceFrameworks: ["BPF", "HACCP", "rotulagem ANVISA"],
    traceabilityFields: ["lote", "validade", "registro", "fabricante"],
  },
  MX: {
    code: "MX",
    name: "Mexico",
    region: "LATAM",
    locale: "es-MX",
    currency: "MXN",
    timezone: "America/Mexico_City",
    taxIdLabel: "RFC",
    taxLabel: "IVA",
    defaultTaxRate: 16,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["mercadopago", "stripe", "paypal", "manual"],
    labelLanguages: ["es"],
    foodAuthorities: ["COFEPRIS", "SENASICA"],
    complianceFrameworks: ["NOM", "HACCP", "BPM"],
    traceabilityFields: ["lote", "caducidad", "registro", "fabricante"],
  },
  CO: {
    code: "CO",
    name: "Colombia",
    region: "LATAM",
    locale: "es-CO",
    currency: "COP",
    timezone: "America/Bogota",
    taxIdLabel: "NIT",
    taxLabel: "IVA",
    defaultTaxRate: 19,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["es"],
    foodAuthorities: ["INVIMA", "ICA"],
    complianceFrameworks: ["BPM", "HACCP", "rotulado INVIMA"],
    traceabilityFields: ["lote", "vencimiento", "registro sanitario", "fabricante"],
  },
  PE: {
    code: "PE",
    name: "Peru",
    region: "LATAM",
    locale: "es-PE",
    currency: "PEN",
    timezone: "America/Lima",
    taxIdLabel: "RUC",
    taxLabel: "IGV",
    defaultTaxRate: 18,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["es"],
    foodAuthorities: ["DIGESA", "SENASA"],
    complianceFrameworks: ["BPM", "HACCP", "rotulado DIGESA"],
    traceabilityFields: ["lote", "vencimiento", "registro sanitario", "origen"],
  },
  US: {
    code: "US",
    name: "United States",
    region: "North America",
    locale: "en-US",
    currency: "USD",
    timezone: "America/New_York",
    taxIdLabel: "EIN",
    taxLabel: "Sales tax",
    defaultTaxRate: 0,
    measurementSystem: "us",
    weightUnit: "lb",
    volumeUnit: "gal",
    temperatureUnit: "fahrenheit",
    dateFormat: "MM/DD/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["en", "es"],
    foodAuthorities: ["FDA", "USDA"],
    complianceFrameworks: ["FSMA", "HACCP", "GMP", "FDA Food Traceability Rule"],
    traceabilityFields: ["lot", "expiration", "facility", "TLC", "CTE", "KDE"],
  },
  CA: {
    code: "CA",
    name: "Canada",
    region: "North America",
    locale: "en-CA",
    currency: "CAD",
    timezone: "America/Toronto",
    taxIdLabel: "Business number",
    taxLabel: "GST/HST",
    defaultTaxRate: 5,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "YYYY-MM-DD",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["en", "fr"],
    foodAuthorities: ["CFIA", "Health Canada"],
    complianceFrameworks: ["SFCR", "HACCP", "PCP"],
    traceabilityFields: ["lot", "expiry", "establishment", "origin"],
  },
  ES: {
    code: "ES",
    name: "Spain",
    region: "Europe",
    locale: "es-ES",
    currency: "EUR",
    timezone: "Europe/Madrid",
    taxIdLabel: "NIF/CIF",
    taxLabel: "IVA",
    defaultTaxRate: 21,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["es"],
    foodAuthorities: ["AESAN", "AICA"],
    complianceFrameworks: ["EU 178/2002", "HACCP", "APPCC", "IFS", "BRCGS"],
    traceabilityFields: ["lote", "caducidad", "registro sanitario", "origen"],
  },
  PT: {
    code: "PT",
    name: "Portugal",
    region: "Europe",
    locale: "pt-PT",
    currency: "EUR",
    timezone: "Europe/Lisbon",
    taxIdLabel: "NIF",
    taxLabel: "IVA",
    defaultTaxRate: 23,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["pt"],
    foodAuthorities: ["ASAE", "DGAV"],
    complianceFrameworks: ["EU 178/2002", "HACCP", "IFS", "BRCGS"],
    traceabilityFields: ["lote", "validade", "registo", "origem"],
  },
  IT: {
    code: "IT",
    name: "Italy",
    region: "Europe",
    locale: "it-IT",
    currency: "EUR",
    timezone: "Europe/Rome",
    taxIdLabel: "Partita IVA",
    taxLabel: "IVA",
    defaultTaxRate: 22,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["it"],
    foodAuthorities: ["Ministero della Salute", "NAS"],
    complianceFrameworks: ["EU 178/2002", "HACCP", "IFS", "BRCGS"],
    traceabilityFields: ["lotto", "scadenza", "stabilimento", "origine"],
  },
  FR: {
    code: "FR",
    name: "France",
    region: "Europe",
    locale: "fr-FR",
    currency: "EUR",
    timezone: "Europe/Paris",
    taxIdLabel: "SIRET",
    taxLabel: "TVA",
    defaultTaxRate: 20,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["fr"],
    foodAuthorities: ["DGAL", "ANSES"],
    complianceFrameworks: ["EU 178/2002", "HACCP", "IFS", "BRCGS"],
    traceabilityFields: ["lot", "DLC/DDM", "etablissement", "origine"],
  },
  DE: {
    code: "DE",
    name: "Germany",
    region: "Europe",
    locale: "de-DE",
    currency: "EUR",
    timezone: "Europe/Berlin",
    taxIdLabel: "USt-IdNr.",
    taxLabel: "MwSt.",
    defaultTaxRate: 19,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["de"],
    foodAuthorities: ["BVL", "BfR"],
    complianceFrameworks: ["EU 178/2002", "HACCP", "IFS", "BRCGS"],
    traceabilityFields: ["charge", "mhd", "betrieb", "herkunft"],
  },
  GB: {
    code: "GB",
    name: "United Kingdom",
    region: "Europe",
    locale: "en-GB",
    currency: "GBP",
    timezone: "Europe/London",
    taxIdLabel: "Company number",
    taxLabel: "VAT",
    defaultTaxRate: 20,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["en"],
    foodAuthorities: ["FSA", "Food Standards Scotland"],
    complianceFrameworks: ["UK Food Law", "HACCP", "SALSA", "BRCGS"],
    traceabilityFields: ["lot", "use by", "establishment", "origin"],
  },
  AU: {
    code: "AU",
    name: "Australia",
    region: "Oceania",
    locale: "en-AU",
    currency: "AUD",
    timezone: "Australia/Sydney",
    taxIdLabel: "ABN",
    taxLabel: "GST",
    defaultTaxRate: 10,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["en"],
    foodAuthorities: ["FSANZ", "DAFF"],
    complianceFrameworks: ["Food Standards Code", "HACCP", "SQF"],
    traceabilityFields: ["lot", "best before", "facility", "origin"],
  },
  NZ: {
    code: "NZ",
    name: "New Zealand",
    region: "Oceania",
    locale: "en-NZ",
    currency: "NZD",
    timezone: "Pacific/Auckland",
    taxIdLabel: "NZBN",
    taxLabel: "GST",
    defaultTaxRate: 15,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["en"],
    foodAuthorities: ["MPI"],
    complianceFrameworks: ["Food Act", "HACCP", "RMP"],
    traceabilityFields: ["lot", "best before", "facility", "origin"],
  },
  ZA: {
    code: "ZA",
    name: "South Africa",
    region: "Africa",
    locale: "en-ZA",
    currency: "ZAR",
    timezone: "Africa/Johannesburg",
    taxIdLabel: "VAT number",
    taxLabel: "VAT",
    defaultTaxRate: 15,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["en"],
    foodAuthorities: ["DALRRD", "SAHPRA"],
    complianceFrameworks: ["Foodstuffs Act", "HACCP", "FSSC 22000"],
    traceabilityFields: ["lot", "best before", "facility", "origin"],
  },
  JP: {
    code: "JP",
    name: "Japan",
    region: "Asia",
    locale: "ja-JP",
    currency: "JPY",
    timezone: "Asia/Tokyo",
    taxIdLabel: "Corporate number",
    taxLabel: "Consumption tax",
    defaultTaxRate: 10,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "YYYY-MM-DD",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["ja", "en"],
    foodAuthorities: ["MHLW", "CAA Japan"],
    complianceFrameworks: ["Food Sanitation Act", "HACCP"],
    traceabilityFields: ["lot", "expiry", "facility", "origin"],
  },
  KR: {
    code: "KR",
    name: "South Korea",
    region: "Asia",
    locale: "ko-KR",
    currency: "KRW",
    timezone: "Asia/Seoul",
    taxIdLabel: "Business registration number",
    taxLabel: "VAT",
    defaultTaxRate: 10,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "YYYY-MM-DD",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["ko", "en"],
    foodAuthorities: ["MFDS"],
    complianceFrameworks: ["Food Sanitation Act", "HACCP"],
    traceabilityFields: ["lot", "expiry", "facility", "origin"],
  },
  CN: {
    code: "CN",
    name: "China",
    region: "Asia",
    locale: "zh-CN",
    currency: "CNY",
    timezone: "Asia/Shanghai",
    taxIdLabel: "USCC",
    taxLabel: "VAT",
    defaultTaxRate: 13,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "YYYY-MM-DD",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["zh", "en"],
    foodAuthorities: ["SAMR", "GACC"],
    complianceFrameworks: ["Food Safety Law", "GB standards", "HACCP"],
    traceabilityFields: ["lot", "expiry", "manufacturer", "origin"],
  },
  IN: {
    code: "IN",
    name: "India",
    region: "Asia",
    locale: "en-IN",
    currency: "INR",
    timezone: "Asia/Kolkata",
    taxIdLabel: "GSTIN",
    taxLabel: "GST",
    defaultTaxRate: 18,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["en", "hi"],
    foodAuthorities: ["FSSAI"],
    complianceFrameworks: ["FSS Act", "HACCP", "FSSAI licensing"],
    traceabilityFields: ["lot", "best before", "license", "origin"],
  },
  SG: {
    code: "SG",
    name: "Singapore",
    region: "Asia",
    locale: "en-SG",
    currency: "SGD",
    timezone: "Asia/Singapore",
    taxIdLabel: "UEN",
    taxLabel: "GST",
    defaultTaxRate: 9,
    measurementSystem: "metric",
    weightUnit: "kg",
    volumeUnit: "l",
    temperatureUnit: "celsius",
    dateFormat: "DD/MM/YYYY",
    billingProviders: ["stripe", "paypal", "manual"],
    labelLanguages: ["en"],
    foodAuthorities: ["SFA"],
    complianceFrameworks: ["Food Regulations", "HACCP", "SS 590"],
    traceabilityFields: ["lot", "expiry", "license", "origin"],
  },
};

export const COUNTRY_OPTIONS = Object.values(COUNTRY_PROFILES).sort((a, b) =>
  a.name.localeCompare(b.name),
);

export function getCountryProfile(code?: string | null): CountryProfile {
  if (!code) return COUNTRY_PROFILES[DEFAULT_COUNTRY_CODE];
  return (
    COUNTRY_PROFILES[code.toUpperCase() as CountryCode] ??
    COUNTRY_PROFILES[DEFAULT_COUNTRY_CODE]
  );
}

export function getDefaultOperatingProfile(code?: string | null) {
  const profile = getCountryProfile(code);
  return {
    country: profile.code,
    locale: profile.locale,
    currency: profile.currency,
    timezone: profile.timezone,
    tax_id_label: profile.taxIdLabel,
    tax_id_value: "",
    tax_label: profile.taxLabel,
    default_tax_rate: profile.defaultTaxRate,
    measurement_system: profile.measurementSystem,
    weight_unit: profile.weightUnit,
    volume_unit: profile.volumeUnit,
    temperature_unit: profile.temperatureUnit,
    date_format: profile.dateFormat,
    compliance_frameworks: profile.complianceFrameworks,
    label_languages: profile.labelLanguages,
    traceability_config: {
      fields: profile.traceabilityFields,
      authorities: profile.foodAuthorities,
      billing_providers: profile.billingProviders,
    },
  };
}
